name: hydroalert
description: Um app Flutter para lembretes de hidratação.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
